import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Sidebar } from "@/components/sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col bg-slate-50">
          <header className="sticky top-0 z-50 h-16 border-b border-slate-200 bg-white flex items-center px-6">
            <div className="flex items-center gap-3">
              <img
                src="/lensically-logo-white-with-black-bg.png"
                alt="Lensically"
                className="h-16 w-16 rounded-md"
              />
              <span className="text-lg font-semibold text-slate-900">
                Lensically
              </span>
            </div>
          </header>

          <div className="flex flex-1">
            <Sidebar />
            <main className="flex-1 p-8">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
