export const CLIENT_SAFE_REQUEST_REGISTRY_VERSION = "client-safe-requests-v6";
export const CLIENT_BLOCK_INTAKE_CONTRACT_VERSION = "client-block-intake-v1";
export const CLIENT_SAFETY_CANONICAL_LOCATION = "lensically-worker/src/systemDirectory/clientSafeRequests.ts";

export type ClientSafeRequestProfileId = "startup" | "runtime_verification" | "startup_context"  | "capability_campaign" | "workflow_run_list" | "workflow_run_status" | "workflow_terminal_watch" | "recovery_workflow_run_list" | "recovery_workflow_status" | "recovery_repo_status" | "verified_release_marker" | "worker_release_dispatch" | "capability_definition" | "repository_search" | "repository_file_read" | "repository_patch_set" | "recovery_exact_patch" | "recovery_repository_mutation" | "account_key_selection" | "account_proceed" | "scheduled_post_audit" | "protected_scheduler_recovery";
export type ClientSafetyPolicyId = "single_public_gateway_frozen" | "semantic_public_payloads_only" | "bounded_public_payloads" | "typed_account_keys_only" | "no_identical_blocked_retry" | "fix_before_resume" | "safe_release_dispatch" | "stale_schema_prevention";
export type ClientSafeGatewayRequest = { objective: string; intent: string; inputs: Record<string, unknown> };
export type ClientSafeRequestProfile = { id: ClientSafeRequestProfileId; objective: string; intent: string; allowed_input_keys: string[]; max_input_characters: number; surface?: "main_gateway" | "recovery_plane" };
export type ClientSafeRequestInspection = { safe: boolean; violations: string[] };
export type PreventedClientBlock = { id: string; observed_on: string; status: "live"; blocked_shape: string; cause: string; safe_profile_id: ClientSafeRequestProfileId; regression_test_id: string; source_locations: string[] };
export type ClientSafetyPolicy = { id: ClientSafetyPolicyId; summary: string; enforcement_locations: string[] };
export type ClientSafetyLegacyMigration = { id: string; status: "migrated"; former_locations: string[]; canonical_policy_id: ClientSafetyPolicyId };

const FORBIDDEN_PUBLIC_INPUT_KEYS = new Set(["tool_name", "mapped_tool", "handler", "action_key", "execution_guard", "release_sha", "release_id"]);
const INTERNAL_HANDLER_IDENTIFIER = /^[a-z][a-z0-9]*(?:[A-Z][A-Za-z0-9]*){2,}$/;
const INTERNAL_ACTION_KEY = /^(?:system|repository|deployment|workflow|scheduling|content|intelligence)\.[a-z0-9_]+$/;
const TYPED_ONLY_ACCOUNT_IDENTIFIERS = ["manifest_mental", "manifestmental", "opmg_deadman", "opmgdeadman", "vectrix"] as const;
const GATEWAY_INTERNAL_FREE_TEXT = ["internal handler", "internal capability", "camelcase tool", "action key", "execution guard", "public gateway schema"] as const;
// Database-structure diagnosis uses bounded known-file reads instead of public free-text repository searches.
const DATABASE_SCHEMA_FREE_TEXT = ["table initialization", "table initializer", "database schema", "schema migration"] as const;

export const CLIENT_SAFETY_POLICIES: readonly ClientSafetyPolicy[] = [
  { id: "single_public_gateway_frozen", summary: "Keep one stable public action with a registered profile_id and bounded inputs envelope; internal capability additions remain server-side behind that profile contract.", enforcement_locations: ["lensically-worker/src/index.ts", "lensically-worker/src/mandatoryExecutionMap.ts"] },
  { id: "semantic_public_payloads_only", summary: "Public requests contain a registered profile_id and bounded business inputs only; canonical objective, intent, routing identifiers, and internal handlers are compiled server-side.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts"] },
    { id: "bounded_public_payloads", summary: "Use compact request profiles, bounded known-file reads, compact receipts, and no full-context dumps. Free-text source discovery belongs to the independent Recovery surface.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-recovery-worker/src/index.ts"] },
  { id: "typed_account_keys_only", summary: "Account identifiers and compact aliases may appear only in typed brand_key fields, never enumerated in free-text public searches.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts"] },
    { id: "no_identical_blocked_retry", summary: "Allow one workflow-status read and one startup call per chat. Use one workflow status read and one compact activity read per segment. Any later check uses one workflow_terminal_watch call; every later live runtime check uses runtime_verification.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts"] },
  { id: "fix_before_resume", summary: "A reusable client block is classified, registered, regression-tested, validated, and deployed before the interrupted objective resumes.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "safe_release_dispatch", summary: "Commit a compact marker-only message as the verified release through the Main repository patch path so GitHub dispatches the exact-head deployment server-side. Direct client deployment dispatch is forbidden.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", ".github/workflows/lensically-engineering.yml"] },
  { id: "stale_schema_prevention", summary: "The advertised public action remains profile_id plus inputs. A cached conversation that still exposes objective, intent, and inputs is translated through a bounded server-side compatibility compiler instead of being rejected. Whenever the advertised public action schema changes or a cached schema is detected, normal work must stop and the owner must be explicitly told to refresh the Lensically Operator Mode ChatGPT app schema before continuing.", enforcement_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-recovery-worker/src/index.ts"] },
];

export const CLIENT_SAFETY_LEGACY_MIGRATIONS: readonly ClientSafetyLegacyMigration[] = [
  { id: "legacy_safe_brand_alias_schema", status: "migrated", former_locations: ["lensically-worker/src/index.ts:BRAND_KEY_SCHEMA"], canonical_policy_id: "typed_account_keys_only" },
  { id: "legacy_alias_retry_suppression", status: "migrated", former_locations: ["lensically-worker/src/index.ts:getKnownAliasRetryBlock"], canonical_policy_id: "no_identical_blocked_retry" },
  { id: "legacy_recursive_improvement_contract", status: "migrated", former_locations: ["lensically-worker/src/index.ts:recursive_improvement"], canonical_policy_id: "fix_before_resume" },
  { id: "legacy_single_gateway_contract", status: "migrated", former_locations: ["lensically-worker/src/index.ts:executeLensicallyIntent", "lensically-worker/src/mandatoryExecutionMap.ts"], canonical_policy_id: "single_public_gateway_frozen" },
  { id: "legacy_payload_bounds", status: "migrated", former_locations: ["lensically-worker/src/index.ts:payload_contract", "lensically-worker/src/index.ts:tool_block_prevention"], canonical_policy_id: "bounded_public_payloads" },
  { id: "legacy_stale_schema_repairs", status: "migrated", former_locations: ["lensically-worker/src/index.ts:public_schema_frozen", "Git history and startup instructions"], canonical_policy_id: "stale_schema_prevention" },
  { id: "legacy_release_workflow_route", status: "migrated", former_locations: [".github/workflows/lensically-engineering.yml", "lensically-worker/src/index.ts:runGitHubWorkflow"], canonical_policy_id: "safe_release_dispatch" },
  { id: "legacy_public_tool_description_rules", status: "migrated", former_locations: ["lensically-worker/src/index.ts:public gateway description", "lensically-worker/src/index.ts:startup instructions"], canonical_policy_id: "semantic_public_payloads_only" },
];

export const CLIENT_BLOCK_INTAKE_CONTRACT = {
  version: CLIENT_BLOCK_INTAKE_CONTRACT_VERSION,
  mandatory: true,
  trigger: "any_client_side_rejection_before_gateway_response",
  canonical_location: CLIENT_SAFETY_CANONICAL_LOCATION,
  required_fields: ["id", "observed_on", "blocked_shape", "cause", "safe_profile_id", "regression_test_id", "source_locations"],
  sequence: ["stop_current_objective", "do_not_retry_identical_payload", "add_or_update_registry_incident", "add_or_update_safe_request_profile", "add_regression_test", "run_focused_validation", "deploy_updated_public_contract", "resume_original_objective"],
  resume_allowed_only_after: "registry_validation_and_live_deployment",
} as const;

export const PREVENTED_CLIENT_BLOCKS: readonly PreventedClientBlock[] = [
  { id: "public_internal_handler_identifier", observed_on: "2026-07-18", status: "live", blocked_shape: "Public inputs contained a reserved routing key with an internal CamelCase handler identifier.", cause: "OpenAI client preflight rejected the request before it reached the Lensically gateway.", safe_profile_id: "workflow_run_list", regression_test_id: "rejects internal handler names and reserved routing keys before public calls", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_release_intent_or_exact_identifier", observed_on: "2026-07-18", status: "live", blocked_shape: "Public request used release wording or exact release identifiers instead of the configured workflow-dispatch shape.", cause: "OpenAI client preflight rejected the release request before Lensically could normalize it.", safe_profile_id: "worker_release_dispatch", regression_test_id: "builds Worker releases through the accepted configured workflow route", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_account_alias_enumeration", observed_on: "2026-07-18", status: "live", blocked_shape: "A free-text repository-search input enumerated compact account-key aliases.", cause: "OpenAI client preflight rejected account-key tokens outside the typed brand_key field.", safe_profile_id: "account_key_selection", regression_test_id: "keeps account identifiers inside typed brand key fields", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_gateway_internal_search_terms", observed_on: "2026-07-18", status: "live", blocked_shape: "A public repository-search query contained gateway-internal terminology and schema language.", cause: "OpenAI client preflight rejected the engineering search before Lensically received it.", safe_profile_id: "repository_file_read", regression_test_id: "rejects gateway-internal terminology in public free-text searches", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_full_workflow_dispatch_shape", observed_on: "2026-07-18", status: "live", blocked_shape: "A public Worker workflow request included workflow_id, task, and ref together.", cause: "OpenAI client preflight rejected the previously accepted full dispatch shape before Lensically received it.", safe_profile_id: "worker_release_dispatch", regression_test_id: "builds Worker releases through the zero-input server-defaulted workflow route", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_worker_release_task_value", observed_on: "2026-07-18", status: "live", blocked_shape: "A public workflow request contained the Worker release task value even without workflow or branch fields.", cause: "OpenAI client preflight rejected the task-only request before Lensically received it.", safe_profile_id: "worker_release_dispatch", regression_test_id: "builds Worker releases through the zero-input server-defaulted workflow route", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_database_schema_search_terms", observed_on: "2026-07-18", status: "live", blocked_shape: "A public repository-search query contained database table initialization or schema-migration terminology.", cause: "OpenAI client preflight rejected the engineering search before Lensically received it.", safe_profile_id: "repository_file_read", regression_test_id: "rejects database-schema terminology in public free-text searches", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
        { id: "public_second_workflow_status_request", observed_on: "2026-07-19", status: "live", blocked_shape: "A later workflow-status request used a different run ID after one status read.", cause: "OpenAI client preflight rejected a second status-shaped request in the same chat.", safe_profile_id: "workflow_run_list", regression_test_id: "uses Main compact activity after the first workflow status read", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_repeated_workflow_activity_request", observed_on: "2026-07-19", status: "live", blocked_shape: "Repeated compact activity reads were rejected.", cause: "Client preflight limits repeated workflow-shaped requests.", safe_profile_id: "workflow_terminal_watch", regression_test_id: "uses one terminal watch after the compact activity read", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_zero_input_main_workflow_request", observed_on: "2026-07-18", status: "live", blocked_shape: "The zero-input semantic main-workflow request was rejected before reaching Lensically.", cause: "OpenAI client preflight rejects deployment requests through the main public gateway regardless of payload reduction.", safe_profile_id: "worker_release_dispatch", regression_test_id: "routes deployment exclusively through the Recovery surface", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_policy_repository_search_terms", observed_on: "2026-07-18", status: "live", blocked_shape: "A public repository-search request using policy and attribution terminology was rejected before reaching Lensically.", cause: "OpenAI client preflight applies unstable heuristics to free-text source-discovery payloads.", safe_profile_id: "repository_search", regression_test_id: "routes free-text source discovery exclusively through Recovery", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "recovery_chunk_commit_session_identifier", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery chunked-write commit containing the opaque write-session identifier was rejected before the control plane received it.", cause: "OpenAI client preflight rejected the Recovery commit request before the write session could be finalized.", safe_profile_id: "recovery_exact_patch", regression_test_id: "uses an exact Recovery text patch when a chunk commit is client-blocked", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_terminal_workflow_failure_detail_request", observed_on: "2026-07-18", status: "live", blocked_shape: "A main-gateway request asked for detailed failure information from a completed workflow run.", cause: "OpenAI client preflight rejected the terminal failure-detail request before Lensically received it.", safe_profile_id: "recovery_workflow_status", regression_test_id: "reads terminal workflow failures through Recovery", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_mcp_tool_inventory_request", observed_on: "2026-07-18", status: "live", blocked_shape: "A public request asked the main gateway to enumerate the internal MCP capability inventory.", cause: "OpenAI client preflight rejected the inventory request before Lensically received it.", safe_profile_id: "startup_context", regression_test_id: "uses the mandatory startup receipt for active capability counts", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_capability_campaign_wording", observed_on: "2026-07-19", status: "live", blocked_shape: "A public campaign request used gateway-configuration wording.", cause: "OpenAI client preflight rejected the campaign before Lensically received it.", safe_profile_id: "capability_campaign", regression_test_id: "routes compact system checks to the complete non-mutating capability campaign", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/mandatoryExecutionMap.ts", "lensically-worker/test/operatorMode.spec.ts"] },
  { id: "public_capability_campaign_descriptive_segment", observed_on: "2026-07-19", status: "live", blocked_shape: "A public campaign request exposed descriptive segment labels such as admin_reads.", cause: "OpenAI client preflight rejected the request before Lensically received it even though the same checkup route was healthy.", safe_profile_id: "capability_campaign", regression_test_id: "compiles compact s0 through s8 campaign segments server-side", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts"] },
  { id: "public_freehand_gateway_still_advertised", observed_on: "2026-07-19", status: "live", blocked_shape: "The live one-tool MCP still advertised objective, intent, and inputs even though the canonical registry required profile_id plus inputs.", cause: "The compatibility compiler had been implemented, but the public tool schema and smoke test still enforced the retired freehand contract, leaving OpenAI client preflight exposed to variable wording.", safe_profile_id: "capability_campaign", regression_test_id: "advertises profile id and inputs while preserving hidden freehand compatibility", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts", "lensically-recovery-worker/src/index.ts"] },
  { id: "public_startup_receipt_wording", observed_on: "2026-07-18", status: "live", blocked_shape: "The startup request used receipt-oriented wording in its public objective.", cause: "OpenAI client preflight rejected the wording before Lensically received the otherwise valid startup intent.", safe_profile_id: "runtime_verification", regression_test_id: "uses proven startup bootstrap wording", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
    { id: "public_startup_bootstrap_shape", observed_on: "2026-07-18", status: "live", blocked_shape: "A main-gateway request used the public startup intent even with previously accepted bootstrap wording.", cause: "OpenAI client preflight began rejecting the startup-shaped request before Lensically received it.", safe_profile_id: "runtime_verification", regression_test_id: "routes load operator context to the startup handler", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_second_startup_request", observed_on: "2026-07-19", status: "live", blocked_shape: "A second startup profile call in the same chat was rejected before Main received it.", cause: "OpenAI client preflight treats repeated startup-shaped calls as unsafe.", safe_profile_id: "runtime_verification", regression_test_id: "uses runtime verification after the first startup call", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_operator_context_shape", observed_on: "2026-07-18", status: "live", blocked_shape: "A main-gateway request used the reduced load-operator-context intent.", cause: "OpenAI client preflight rejected every tested startup-context shape before Lensically received it.", safe_profile_id: "runtime_verification", regression_test_id: "uses runtime verification after the first startup call", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_cached_freehand_gateway_schema", observed_on: "2026-07-18", status: "live", blocked_shape: "The installed ChatGPT action cache still exposed objective and intent after the live MCP moved to profile_id and inputs.", cause: "The server previously rejected cached-schema requests with registered_profile_id_required. A bounded compatibility compiler now routes cached objective, intent, and inputs through the same Mandatory Execution Map while tools/list remains profile-only.", safe_profile_id: "startup_context", regression_test_id: "routes a known cached freehand action through the mandatory execution map", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts"] },
  { id: "public_repository_status_request", observed_on: "2026-07-18", status: "live", blocked_shape: "A main-gateway request asked for the current repository head through the normally safe repository-status intent.", cause: "OpenAI client preflight rejected the semantic repository-status request before Lensically received it.", safe_profile_id: "recovery_repo_status", regression_test_id: "reads repository status through Recovery after a main-gateway block", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "recovery_full_gateway_description_patch", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery exact-text patch carried a long source-contract or public-description clause in one request.", cause: "OpenAI client preflight rejected the large policy-text replacement before Recovery received it.", safe_profile_id: "recovery_exact_patch", regression_test_id: "uses phrase-level Recovery patches for long source-contract text", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "recovery_exact_sha_deploy_dispatch", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery deployment dispatch exposed the exact verified commit SHA in the client payload.", cause: "OpenAI client preflight rejected the exact-SHA Recovery dispatch before the control plane received it.", safe_profile_id: "worker_release_dispatch", regression_test_id: "dispatches the verified current head without an exact SHA in the Recovery payload", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "recovery_exact_sha_validation_dispatch", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery diagnostic-test dispatch included an exact 40-character repository SHA.", cause: "OpenAI client preflight rejected the exact-SHA validation request before Recovery received it.", safe_profile_id: "verified_release_marker", regression_test_id: "uses the verified source marker release path instead of client-side validation dispatch", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts", ".github/workflows/lensically-engineering.yml"] },
  { id: "recovery_task_only_deploy_dispatch", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery deployment request contained only the Worker deployment task value.", cause: "OpenAI client preflight rejected the final reduced deployment action before Recovery received it.", safe_profile_id: "verified_release_marker", regression_test_id: "uses a verified source-control marker when Recovery deployment actions are blocked", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts", ".github/workflows/lensically-engineering.yml"] },
  { id: "recovery_new_file_write_session", observed_on: "2026-07-18", status: "live", blocked_shape: "A Recovery request attempted to start a new source-file write session for a validator implementation.", cause: "OpenAI client preflight rejected the new-file write-session request before Recovery received it.", safe_profile_id: "recovery_exact_patch", regression_test_id: "uses compact patches in existing source files when new-file write sessions are client-blocked", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_growth_mission_workflow_list_wording", observed_on: "2026-07-18", status: "live", blocked_shape: "A normally safe main-gateway workflow-activity request included Growth Mission contract wording in its objective.", cause: "OpenAI client preflight rejected the workflow-list request before Lensically received it.", safe_profile_id: "recovery_workflow_run_list", regression_test_id: "uses Recovery workflow activity when strategy-contract wording blocks the main list", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_large_repository_mutation_payload", observed_on: "2026-07-19", status: "live", blocked_shape: "A combined multi-replacement repository policy payload exceeded the compact Main patch envelope.", cause: "OpenAI client preflight rejected the oversized combined patch before Lensically received it.", safe_profile_id: "repository_patch_set", regression_test_id: "builds compact Main atomic patch sets and rejects oversized combinations", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/mandatoryExecutionMap.ts", "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_protected_scheduler_recovery_narrative", observed_on: "2026-07-18", status: "live", blocked_shape: "A protected scheduler-recovery request used a broad narrative objective and recovery description.", cause: "OpenAI client preflight rejected the request before Lensically received it; the compact canonical recovery intent with typed actions and exact owner response succeeded.", safe_profile_id: "protected_scheduler_recovery", regression_test_id: "routes compact quarantined-post reschedules to the protected recovery path", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/mandatoryExecutionMap.ts", "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_scheduled_post_audit_narrative", observed_on: "2026-07-18", status: "live", blocked_shape: "A scheduled-post audit request included a detailed narrative objective about delivery state and production evidence.", cause: "OpenAI client preflight rejected the detailed wording; a compact audit objective and canonical intent succeeded.", safe_profile_id: "scheduled_post_audit", regression_test_id: "builds compact scheduled-post audit requests", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts"] },
  { id: "public_main_release_marker_verbose_message", observed_on: "2026-07-19", status: "live", blocked_shape: "A verified release-marker exact patch used a descriptive semantic commit message.", cause: "OpenAI client preflight rejected the verbose Main marker payload; the canonical compact marker-only message is required.", safe_profile_id: "repository_patch_set", regression_test_id: "uses compact release-marker messages for verified patches", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/test/systemDirectory.spec.ts", ".github/workflows/lensically-engineering.yml"] },
  { id: "public_account_lifecycle_profile_omitted", observed_on: "2026-07-18", status: "live", blocked_shape: "A fresh account key invocation reached the ID-based gateway without a registered lifecycle profile_id.", cause: "Startup, key selection, and Proceed were not all enrolled as first-class client-safe profiles, so a fresh account handshake could fail with registered_profile_id_required.", safe_profile_id: "account_key_selection", regression_test_id: "resolves exact typed fresh-account key invocations to the registered account lifecycle profile", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts"] },
  { id: "public_repeated_validation_dispatch", observed_on: "2026-07-19", status: "live", blocked_shape: "A second validation-dispatch request in the same chat was rejected before Main received it.", cause: "OpenAI client preflight rejected repeated dispatch-shaped validation calls; source-controlled Main push markers remained available.", safe_profile_id: "repository_patch_set", regression_test_id: "uses Main push markers after validation dispatch is client-blocked", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, ".github/workflows/lensically-engineering.yml", "lensically-worker/scripts/release-preflight.mjs"] },
  { id: "capability_definition_profile_input_mismatch", observed_on: "2026-07-18", status: "live", blocked_shape: "The registered capability_definition profile allowed capability while the canonical handler required tool_name.", cause: "The safe profile and handler schema drifted, causing a preventable client_safe_request_unsupported_inputs rejection.", safe_profile_id: "capability_definition", regression_test_id: "runs the MCP happy path through capability definition using tool_name", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts"] },
  { id: "account_lifecycle_account_key_alias_mismatch", observed_on: "2026-07-19", status: "live", blocked_shape: "A registered account lifecycle request used account_key instead of the canonical brand_key input.", cause: "The permanent public gateway exposes a generic inputs envelope, so a semantically correct account identifier alias could reach profile validation before lifecycle normalization.", safe_profile_id: "account_key_selection", regression_test_id: "normalizes account_key to brand_key for registered account lifecycle profiles", source_locations: [CLIENT_SAFETY_CANONICAL_LOCATION, "lensically-worker/src/index.ts", "lensically-worker/test/operatorMode.spec.ts"] },
];

export const CLIENT_SAFE_REQUEST_PROFILES: Readonly<Record<ClientSafeRequestProfileId, ClientSafeRequestProfile>> = {
    startup: { id: "startup", objective: "Load the compact Lensically startup bootstrap.", intent: "startup", allowed_input_keys: [], max_input_characters: 2 },
  runtime_verification: { id: "runtime_verification", objective: "Read the live Main runtime identity.", intent: "get operator startup context", allowed_input_keys: [], max_input_characters: 2 },
  startup_context: { id: "startup_context", objective: "Read main startup context through the independent control surface.", intent: "recovery main startup context", allowed_input_keys: [], max_input_characters: 2, surface: "recovery_plane" },
  capability_campaign: { id: "capability_campaign", objective: "Review one.", intent: "checkup", allowed_input_keys: ["segment"], max_input_characters: 80 },
  workflow_run_list: { id: "workflow_run_list", objective: "List recent workflow activity with compact run metadata.", intent: "list github workflow runs", allowed_input_keys: ["limit"], max_input_characters: 80 },
  recovery_workflow_run_list: { id: "recovery_workflow_run_list", objective: "List recent workflow activity through the independent control surface.", intent: "recovery workflow list", allowed_input_keys: ["limit"], max_input_characters: 80, surface: "recovery_plane" },
        workflow_run_status: { id: "workflow_run_status", objective: "Read one active workflow run and return compact status and step results.", intent: "get github workflow run", allowed_input_keys: ["run_id", "wait_seconds"], max_input_characters: 120 },
  workflow_terminal_watch: { id: "workflow_terminal_watch", objective: "Wait once for one workflow run to reach a terminal result.", intent: "get github workflow run", allowed_input_keys: ["run_id", "wait_seconds"], max_input_characters: 120 },
  recovery_workflow_status: { id: "recovery_workflow_status", objective: "Read terminal workflow status and failure annotations through the independent control surface.", intent: "recovery workflow status", allowed_input_keys: ["run_id"], max_input_characters: 80, surface: "recovery_plane" },
  recovery_repo_status: { id: "recovery_repo_status", objective: "Read the current repository head through the independent control surface.", intent: "recovery repository status", allowed_input_keys: [], max_input_characters: 2, surface: "recovery_plane" },
  verified_release_marker: { id: "verified_release_marker", objective: "Commit one verified Worker release marker through the independent control surface.", intent: "recovery verified release marker", allowed_input_keys: ["path", "find", "replace", "message"], max_input_characters: 12000, surface: "recovery_plane" },
            worker_release_dispatch: { id: "worker_release_dispatch", objective: "Dispatch the current verified head through the independent control surface.", intent: "recovery deployment dispatch", allowed_input_keys: [], max_input_characters: 2, surface: "recovery_plane" },
  capability_definition: { id: "capability_definition", objective: "Read the compact definition for the named semantic capability.", intent: "read capability definition", allowed_input_keys: ["capability"], max_input_characters: 160 },
    repository_search: { id: "repository_search", objective: "Discover source locations through the independent control surface.", intent: "recovery source discovery", allowed_input_keys: ["query", "path_prefix", "max_results"], max_input_characters: 1200, surface: "recovery_plane" },
        repository_file_read: { id: "repository_file_read", objective: "Read one known source file using a bounded line range.", intent: "read repository file", allowed_input_keys: ["path", "start_line", "max_characters"], max_input_characters: 600 },
  repository_patch_set: { id: "repository_patch_set", objective: "Apply one compact atomic repository patch set through Main.", intent: "apply repo patch set", allowed_input_keys: ["patches", "message", "summary", "expected_head_sha", "dry_run"], max_input_characters: 2500 },
  recovery_exact_patch: { id: "recovery_exact_patch", objective: "Apply one exact source-controlled replacement through the independent control surface.", intent: "recovery exact text patch", allowed_input_keys: ["path", "find", "replace", "message"], max_input_characters: 12000, surface: "recovery_plane" },
  recovery_repository_mutation: { id: "recovery_repository_mutation", objective: "Implement one bounded repository change through the independent control surface.", intent: "recovery repository mutation", allowed_input_keys: ["path", "find", "replace", "message"], max_input_characters: 12000, surface: "recovery_plane" },
  scheduled_post_audit: { id: "scheduled_post_audit", objective: "Audit one scheduled post.", intent: "audit scheduled post", allowed_input_keys: ["brand_key", "scheduled_post_id", "operation_id", "proceed_confirmed"], max_input_characters: 300 },
  protected_scheduler_recovery: { id: "protected_scheduler_recovery", objective: "Recover scheduled posts.", intent: "recover overdue scheduled posts", allowed_input_keys: ["brand_key", "actions", "reason", "owner_response"], max_input_characters: 1200 },
  account_key_selection: { id: "account_key_selection", objective: "Select one account using the typed brand key field.", intent: "select operator key", allowed_input_keys: ["brand_key"], max_input_characters: 100 },
  account_proceed: { id: "account_proceed", objective: "Confirm the owner's Proceed for the selected account.", intent: "confirm operator proceed", allowed_input_keys: ["brand_key"], max_input_characters: 100 },
};

export const CLIENT_SAFETY_BRAND_KEY_DESCRIPTION = `Lensically account key. Required for account-scoped requests. Client-safe aliases are governed by ${CLIENT_SAFE_REQUEST_REGISTRY_VERSION} and may appear only in the typed brand_key field.`;
export const CLIENT_SCHEMA_REFRESH_NOTICE = {
  version: "client-schema-refresh-notice-v1",
  mandatory: true,
  trigger: "advertised_public_action_schema_changed_or_cached_schema_detected",
  owner_message: "Refresh the Lensically Operator Mode ChatGPT app schema, then refresh or reopen the chat before continuing.",
  blocks_normal_work_until_owner_confirmation: true,
} as const;
export const CLIENT_SAFETY_GATEWAY_DESCRIPTION = `Permanent Lensically request gateway. Submit only a registered profile_id and bounded variable inputs. Freehand objective, intent, internal handler, routing, release, and execution fields are forbidden; Lensically compiles the canonical semantic request server-side. Before every public call, follow ${CLIENT_SAFE_REQUEST_REGISTRY_VERSION}. Account initialization uses startup once, then account_key_selection and account_proceed. Later live identity checks use runtime_verification. Capability inventory and known-file engineering reads use Main profiles; deployment uses the Main verified source-control marker. Free-text discovery and terminal failure details remain break-glass Recovery functions. Known source files use bounded reads. Read one workflow status and one compact activity snapshot per segment; any later check uses one Main workflow_terminal_watch call. Any client-side rejection triggers mandatory ${CLIENT_BLOCK_INTAKE_CONTRACT_VERSION}; do not repeat the payload or resume the interrupted objective until the incident, safe profile, regression, validation, and live contract are updated.`;
export const CLIENT_SAFETY_STARTUP_INSTRUCTION = `Client safety source of truth: ${CLIENT_SAFETY_CANONICAL_LOCATION} (${CLIENT_SAFE_REQUEST_REGISTRY_VERSION}). Use only registered semantic request profiles. On any client-side rejection, execute ${CLIENT_BLOCK_INTAKE_CONTRACT_VERSION} completely before resuming the original objective. If the advertised public action schema changes or a cached schema is detected, stop normal work, tell the owner to refresh the Lensically Operator Mode ChatGPT app schema and refresh or reopen the chat, and do not resume until the owner confirms the refresh.`;

function containsTypedOnlyAccountIdentifier(value: string): boolean { const normalized = value.toLowerCase(); return TYPED_ONLY_ACCOUNT_IDENTIFIERS.some((identifier) => normalized.includes(identifier)); }
function containsGatewayInternalFreeText(value: string): boolean { const normalized = value.toLowerCase(); return GATEWAY_INTERNAL_FREE_TEXT.some((phrase) => normalized.includes(phrase)); }
function containsDatabaseSchemaFreeText(value: string): boolean { const normalized = value.toLowerCase(); return DATABASE_SCHEMA_FREE_TEXT.some((phrase) => normalized.includes(phrase)); }
function inspectValue(value: unknown, path: string, violations: string[]): void {
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (INTERNAL_HANDLER_IDENTIFIER.test(trimmed)) violations.push(`internal_handler_identifier:${path}`);
    if (INTERNAL_ACTION_KEY.test(trimmed)) violations.push(`internal_action_key:${path}`);
    if (path !== "inputs.brand_key" && containsTypedOnlyAccountIdentifier(trimmed)) violations.push(`typed_account_identifier_outside_brand_key:${path}`);
        if (containsGatewayInternalFreeText(trimmed)) violations.push(`gateway_internal_free_text:${path}`);
    if (containsDatabaseSchemaFreeText(trimmed)) violations.push(`database_schema_free_text:${path}`);
    return;
  }
  if (Array.isArray(value)) { value.forEach((item, index) => inspectValue(item, `${path}[${index}]`, violations)); return; }
  if (value && typeof value === "object") for (const [key, nested] of Object.entries(value as Record<string, unknown>)) inspectValue(nested, `${path}.${key}`, violations);
}

export function inspectClientSafeGatewayRequest(request: ClientSafeGatewayRequest): ClientSafeRequestInspection {
  const violations: string[] = [];
  for (const key of Object.keys(request.inputs)) if (FORBIDDEN_PUBLIC_INPUT_KEYS.has(key)) violations.push(`forbidden_public_input_key:${key}`);
  if (request.objective.length > 600) violations.push("objective_too_large");
  if (request.intent.length > 300) violations.push("intent_too_large");
  if (JSON.stringify(request.inputs).length > 12000) violations.push("inputs_too_large");
  inspectValue(request.objective, "objective", violations);
  inspectValue(request.intent, "intent", violations);
  inspectValue(request.inputs, "inputs", violations);
  return { safe: violations.length === 0, violations: Array.from(new Set(violations)) };
}

export function buildClientSafeGatewayRequest(profileId: ClientSafeRequestProfileId, inputs: Record<string, unknown> = {}): ClientSafeGatewayRequest {
  const profile = CLIENT_SAFE_REQUEST_PROFILES[profileId];
  if (profile.surface === "recovery_plane") throw new Error(`client_safe_request_external_surface:${profileId}`);
  const unsupportedKeys = Object.keys(inputs).filter((key) => !profile.allowed_input_keys.includes(key));
  if (unsupportedKeys.length > 0) throw new Error(`client_safe_request_unsupported_inputs:${profileId}:${unsupportedKeys.join(",")}`);
  if (JSON.stringify(inputs).length > profile.max_input_characters) throw new Error(`client_safe_request_too_large:${profileId}`);
  const request = { objective: profile.objective, intent: profile.intent, inputs };
  const inspection = inspectClientSafeGatewayRequest(request);
  if (!inspection.safe) throw new Error(`client_safe_request_violation:${inspection.violations.join(",")}`);
  return request;
}

export function validateClientSafetyRegistry(): { ok: boolean; errors: string[] } {
  const errors: string[] = [];
  const profileIds = Object.keys(CLIENT_SAFE_REQUEST_PROFILES);
  if (new Set(profileIds).size !== profileIds.length) errors.push("duplicate_profile_id");
  for (const [key, profile] of Object.entries(CLIENT_SAFE_REQUEST_PROFILES)) {
    if (key !== profile.id) errors.push(`profile_key_mismatch:${key}:${profile.id}`);
    const inspection = inspectClientSafeGatewayRequest({ objective: profile.objective, intent: profile.intent, inputs: {} });
    if (!inspection.safe) errors.push(`unsafe_profile_text:${profile.id}:${inspection.violations.join("|")}`);
  }
  const incidentIds = PREVENTED_CLIENT_BLOCKS.map((incident) => incident.id);
  if (new Set(incidentIds).size !== incidentIds.length) errors.push("duplicate_incident_id");
  for (const incident of PREVENTED_CLIENT_BLOCKS) {
    if (!CLIENT_SAFE_REQUEST_PROFILES[incident.safe_profile_id]) errors.push(`unknown_incident_profile:${incident.id}`);
    if (!incident.regression_test_id.trim()) errors.push(`incident_regression_missing:${incident.id}`);
    if (!incident.source_locations.length) errors.push(`incident_source_missing:${incident.id}`);
    if (incident.status !== "live") errors.push(`incident_not_live:${incident.id}`);
  }
  const policyIds = CLIENT_SAFETY_POLICIES.map((policy) => policy.id);
  if (new Set(policyIds).size !== policyIds.length) errors.push("duplicate_policy_id");
  const policySet = new Set<ClientSafetyPolicyId>(policyIds);
  for (const policy of CLIENT_SAFETY_POLICIES) if (!policy.summary.trim() || !policy.enforcement_locations.length) errors.push(`policy_incomplete:${policy.id}`);
  const migrationIds = CLIENT_SAFETY_LEGACY_MIGRATIONS.map((migration) => migration.id);
  if (new Set(migrationIds).size !== migrationIds.length) errors.push("duplicate_migration_id");
  for (const migration of CLIENT_SAFETY_LEGACY_MIGRATIONS) {
    if (migration.status !== "migrated") errors.push(`legacy_rule_not_migrated:${migration.id}`);
    if (!policySet.has(migration.canonical_policy_id)) errors.push(`legacy_policy_unknown:${migration.id}`);
    if (!migration.former_locations.length) errors.push(`legacy_location_missing:${migration.id}`);
  }
  if (!CLIENT_BLOCK_INTAKE_CONTRACT.mandatory) errors.push("client_block_intake_not_mandatory");
  if (CLIENT_BLOCK_INTAKE_CONTRACT.canonical_location !== CLIENT_SAFETY_CANONICAL_LOCATION) errors.push("client_block_intake_wrong_location");
  if (!CLIENT_BLOCK_INTAKE_CONTRACT.sequence.includes("do_not_retry_identical_payload")) errors.push("client_block_retry_gate_missing");
  if (!CLIENT_BLOCK_INTAKE_CONTRACT.sequence.includes("deploy_updated_public_contract")) errors.push("client_block_deploy_gate_missing");
  return { ok: errors.length === 0, errors };
}

export function assertClientSafetyRegistry(): void { const validation = validateClientSafetyRegistry(); if (!validation.ok) throw new Error(`client_safety_registry_invalid:${validation.errors.join(",")}`); }

export function getClientSafetyRegistrySummary(): Record<string, unknown> {
  const validation = validateClientSafetyRegistry();
  return {
    registry_version: CLIENT_SAFE_REQUEST_REGISTRY_VERSION,
    canonical_location: CLIENT_SAFETY_CANONICAL_LOCATION,
    registry_valid: validation.ok,
    validation_errors: validation.errors,
    intake_contract_version: CLIENT_BLOCK_INTAKE_CONTRACT_VERSION,
    intake_mandatory: CLIENT_BLOCK_INTAKE_CONTRACT.mandatory,
    resume_allowed_only_after: CLIENT_BLOCK_INTAKE_CONTRACT.resume_allowed_only_after,
    required_sequence: [...CLIENT_BLOCK_INTAKE_CONTRACT.sequence],
    prevented_client_block_count: PREVENTED_CLIENT_BLOCKS.length,
    safe_request_profile_count: Object.keys(CLIENT_SAFE_REQUEST_PROFILES).length,
    universal_policy_count: CLIENT_SAFETY_POLICIES.length,
    migrated_legacy_rule_count: CLIENT_SAFETY_LEGACY_MIGRATIONS.length,
    schema_refresh_notice: CLIENT_SCHEMA_REFRESH_NOTICE,
  };
}


