import { BRAND_KEY_SCHEMA } from "./operatorMcpSchemas";
import type { OperatorMcpToolDefinition } from "./operatorMcpToolDefinitions";

export const OPERATOR_MCP_MANIFEST_CYCLE_TOOL_NAMES = [
  "get_manifest_intelligence_foundation",
  "get_manifest_cycle_receipt",
  "record_manifest_cycle_defect",
  "resolve_manifest_cycle_defect",
  "get_manifest_cycle_analysis_page",
  "commit_manifest_cycle_strategy",
] as const;

export type OperatorMcpManifestCycleToolName = typeof OPERATOR_MCP_MANIFEST_CYCLE_TOOL_NAMES[number];

export const OPERATOR_MCP_MANIFEST_CYCLE_TOOLS: OperatorMcpToolDefinition[] = [
  {
    name: "get_manifest_intelligence_foundation",
    title: "Get Manifest intelligence foundation",
    description: "Read the active noninterference and follower-attribution policies, latest durable strategy version, and latest autonomous cycle receipt. This is read-only and returns unavailable states without treating them as failures.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "get_manifest_cycle_receipt",
    title: "Get Manifest autonomous cycle receipt",
    description: "Read one canonical autonomous-cycle receipt without payload-budget truncation. The response always includes a stable summary. Events, hypotheses, defects, and exposure records are pageable; startup state, strategy versions, exposure dimensions, completion, and unresolved issues are reconstructable from canonical stable-JSON chunks.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, cycle_id: { type: "string" }, cycle_operation_id: { type: "string" }, receipt_section: { type: "string", enum: ["summary", "events", "hypotheses", "defects", "exposure_published", "exposure_scheduled", "exposure_dimensions", "startup_state", "input_strategy", "output_strategy", "completion", "unresolved_issues"], default: "summary" }, offset: { type: "integer", minimum: 0, default: 0 }, limit: { type: "integer", minimum: 1, maximum: 10, default: 10 } }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "record_manifest_cycle_defect",
    title: "Record Manifest cycle defect",
    description: "Attach one durable defect receipt to an active Manifest cycle for a failure observed outside the Worker, such as an OpenAI pre-call block, client schema rejection, transport interruption, or ambiguous response. Internal Worker failures are recorded automatically.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        cycle_id: { type: "string" },
        defect_key: { type: "string" },
        stage_number: { type: "integer", minimum: 1, maximum: 7 },
        stage_key: { type: "string" },
        phase: { type: "string" },
        slot_key: { type: "string" },
        operation_id: { type: "string" },
        error_code: { type: "string" },
        error_message: { type: "string" },
        impact_state: { type: "string", enum: ["definitely_failed", "possibly_succeeded", "partially_succeeded", "succeeded_before_response_failed"] },
        retryable: { type: "boolean" },
        blocking: { type: "boolean" },
        status: { type: "string", enum: ["open", "repairing"] },
        reconciliation: { type: "object", additionalProperties: true },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["brand_key", "cycle_id", "defect_key", "stage_number", "stage_key", "phase", "error_code", "error_message", "impact_state"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "resolve_manifest_cycle_defect",
    title: "Resolve Manifest cycle defect",
    description: "Resolve or classify one existing Manifest cycle defect with root cause, repair commit, deployed SHA, regression tests, reconciliation, and live verification evidence. The defect remains permanently attached to the cycle receipt.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        cycle_id: { type: "string" },
        defect_key: { type: "string" },
        status: { type: "string", enum: ["resolved", "irrecoverable_historical_gap"] },
        root_cause: { type: "string" },
        repair_commit_sha: { type: "string" },
        deployed_sha: { type: "string" },
        reconciliation: { type: "object", additionalProperties: true },
        regression_tests: { type: "array", items: { type: "object", additionalProperties: true } },
        verification: { type: "object", additionalProperties: true },
      },
      required: ["brand_key", "cycle_id", "defect_key", "root_cause", "verification"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "get_manifest_cycle_analysis_page",
    title: "Consume Manifest cycle analysis page",
    description: "Return one complete canonical page from the rolling 28-day Manifest evidence snapshot and durably record that the model consumed it. Preparation returns only the snapshot manifest; call this tool from page 0 through the final page before committing the cycle strategy.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        cycle_id: { type: "string" },
        snapshot_id: { type: "string" },
        page_index: { type: "integer", minimum: 0 },
      },
      required: ["brand_key", "cycle_id", "snapshot_id", "page_index"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "commit_manifest_cycle_strategy",
    title: "Lock Manifest cycle strategy",
    description: "After every rolling 28-day analysis page has been consumed, persist exactly one account-wide strategy and a complete source-card-backed lineup for every authoritative missing slot. The model must rank mature posts primarily by 24-hour likes, cite actual post IDs, separate uncertainty from conclusions, and may not create original posts or source-independent hypotheses. Replaying an identical strategy is safe; a conflicting second strategy is blocked.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        cycle_id: { type: "string" },
        snapshot_id: { type: "string" },
        account_conclusion: { type: "object", additionalProperties: true },
        content_focus: { type: "object", additionalProperties: true },
        benchmarks: { type: "object", additionalProperties: true },
        strongest_executions: { type: "array", items: { type: "object", additionalProperties: true } },
        weakest_executions: { type: "array", items: { type: "object", additionalProperties: true } },
        directives: { type: "object", additionalProperties: true },
        experiments: { type: "array", items: { type: "object", additionalProperties: true } },
        risks: { type: "array", items: {} },
        lineup: {
          type: "array",
          minItems: 1,
          items: {
            type: "object",
            properties: {
              slot_key: { type: "string" },
              family_key: { type: "string" },
              strategic_role: { type: "string" },
              generation_mode: { type: "string", enum: ["franchise_deployment", "controlled_variation", "mechanism_expansion", "adjacent_experiment"] },
              source_kind: { type: "string", enum: ["saved_pattern", "source_card"] },
              source_card_id: { type: "string" },
              source_selection_id: { type: "string" },
              audience_reward: { type: "string" },
              hook_direction: { type: "string" },
              placement_reason: { type: "string" },
              nearby_avoid: { type: "array", items: { type: "string" } },
              exploration_mode: { type: "string", enum: ["exploit", "explore", "hybrid"] },
            },
            required: ["slot_key", "family_key", "strategic_role", "generation_mode", "source_kind", "source_card_id", "audience_reward", "hook_direction", "placement_reason", "exploration_mode"],
            additionalProperties: false,
          },
        },
      },
      required: ["brand_key", "cycle_id", "snapshot_id", "account_conclusion", "content_focus", "benchmarks", "strongest_executions", "weakest_executions", "directives", "experiments", "risks", "lineup"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
];
