import {
  BRAND_KEY_SCHEMA,
  GENERATION_ADAPTATION_PLAN_SCHEMA,
  SOURCE_DRAFT_ANALYSIS_SCHEMA,
  SOURCE_TRANSFORMATION_CONTRACT_SCHEMA,
} from "./operatorMcpSchemas";
import type { OperatorMcpToolDefinition } from "./operatorMcpToolDefinitions";

export const OPERATOR_MCP_SOURCE_DRAFT_TOOL_NAMES = [
  "create_source_card",
  "lock_source_card",
  "get_source_card",
  "create_generation_run",
  "run_gates",
  "submit_candidate_draft",
  "mark_draft_shown",
  "save_self_rejected_draft",
  "approve_draft",
  "reject_draft",
  "list_active_gates",
  "create_or_update_gate",
  "promote_memory_to_gate",
] as const;

export type OperatorMcpSourceDraftToolName = typeof OPERATOR_MCP_SOURCE_DRAFT_TOOL_NAMES[number];

export const OPERATOR_MCP_SOURCE_DRAFT_TOOLS: OperatorMcpToolDefinition[] = [
  {
    name: "create_source_card",
    title: "Create source card",
    description: "Create or resolve a canonical structured source card. Manifest selections automatically reuse the current card for the same stable Threads source. Set create_new_version=true with version_reason only when the source interpretation itself changes. For Manifest, build a close-mimicry source contract: preserve the original hook, structure, meaning, tone, and payoff; require only slight wording changes; do not invent scenes, characters, activities, settings, events, metaphors, or premises. Transformation lists are optional and internal-only. During owner review, never present raw Must preserve, May reuse, Must change, Cannot repeat, Pass conditions, or Fail conditions headings; translate the card into the natural owner_presentation format returned by the tool.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        sequence_label: { type: "string" },
        lane_key: { type: "string" },
        title: { type: "string" },
        source_selection_id: { type: "string", description: "Links the source card to one persisted source selection and its immutable metric snapshot." },
        saved_pattern_id: { type: "integer", minimum: 1, description: "Manifest source-card backfill mode. Creates the Saved Pattern's durable source selection internally and locks the newly created card so it is immediately usable." },
        create_new_version: { type: "boolean", description: "Default false. Use only when evidence changes the durable interpretation of the source itself; ordinary new payoffs or experiments belong in a new generation run." },
        version_reason: { type: "string", description: "Required when create_new_version=true. Explains why the canonical source interpretation changed." },
        transformation_contract: SOURCE_TRANSFORMATION_CONTRACT_SCHEMA,
        primary_source: { type: "object", additionalProperties: true },
        secondary_sources: { type: "array", items: { type: "object", additionalProperties: true } },
        anti_sources: { type: "array", items: { type: "object", additionalProperties: true } },
        metrics_snapshot: { type: "object", additionalProperties: true },
        source_mechanism: { type: "string" },
        required_product: { type: "string" },
        forbidden_surfaces: { type: "array", items: {} },
        danger_surfaces: { type: "array", items: {} },
        current_inventory_constraints: { type: "array", items: {} },
        pass_conditions: { type: "array", items: {} },
        fail_conditions: { type: "array", items: {} },
        recommended_direction: { type: "string" },
        context_admission_id: { type: "string" },
      },
      required: ["brand_key", "title", "source_mechanism", "required_product", "forbidden_surfaces", "pass_conditions", "fail_conditions"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "lock_source_card",
    title: "Lock source card",
    description: "Use this to lock a complete source card before serious draft generation or showing candidates.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, source_card_id: { type: "string" } }, required: ["brand_key", "source_card_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "get_source_card",
    title: "Get source card",
    description: "Retrieve a source card plus its canonical family, immutable version history, prior generation plans, drafts, published posts, and metric snapshots. Set include_history=false only when a compact card-only read is necessary. Raw source-card schema and transformation fields are internal persistence/gate data; owner-facing review must follow the returned owner_presentation contract instead of exposing those fields as headings.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, source_card_id: { type: "string" }, include_history: { type: "boolean", default: true } }, required: ["brand_key", "source_card_id"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "create_generation_run",
    title: "Create generation run",
    description: "Create one new adaptation from a locked canonical source-card version. For Manifest, stay as close to the source as possible: heavily mimic the hook, keep the same structure, meaning, tone, and payoff, and make only slight wording changes. Do not invent any new scene or premise. The run persists a compact explicit-hard-ban context for fresh-chat continuity. After source-card approval, continue silently through generation and gates until a showable draft is ready.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, source_card_id: { type: "string" }, adaptation_plan: GENERATION_ADAPTATION_PLAN_SCHEMA, objective: { type: "string", description: "Legacy optional field. Keep omitted or neutral; it must not steer the saved workflow." }, prompt_summary: { type: "string" } }, required: ["brand_key", "source_card_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "run_gates",
    title: "Run operator gates",
    description: "Evaluate source-card or draft gates. For Manifest, close source mimicry is preferred: preserve the hook, structure, meaning, tone, and payoff; block an exact source copy, explicit owner hard bans, and missing required gates. Do not require semantic review of every rejected draft or model fingerprint evidence. Gate evaluation remains silent after source-card approval.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, source_card_id: { type: "string" }, draft_text: { type: "string" }, stage: { type: "string" }, lane_key: { type: "string" }, content_type: { type: "string" }, draft_analysis: SOURCE_DRAFT_ANALYSIS_SCHEMA, model_gate_results: { type: "array", items: { type: "object", additionalProperties: true } } }, required: ["brand_key", "stage"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "submit_candidate_draft",
    title: "Submit candidate draft",
    description: "Save a candidate draft, record source-contract evidence, run all mandatory gates, persist results, and learn whether the draft is showable. For Manifest, the backend allows close source mimicry and blocks only an exact source copy, explicit owner hard bans, inventory collisions not authorized by the source hook, and missing required gate execution. No historical model-review evidence is required. Only present the draft when showable=true.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, run_id: { type: "string" }, source_card_id: { type: "string" }, text: { type: "string" }, draft_index: { type: "integer" }, score: { type: "object", additionalProperties: true }, strategy: { type: "object", additionalProperties: true }, draft_analysis: SOURCE_DRAFT_ANALYSIS_SCHEMA, model_gate_results: { type: "array", items: { type: "object", additionalProperties: true } } }, required: ["brand_key", "run_id", "source_card_id", "text", "draft_analysis"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "mark_draft_shown",
    title: "Mark draft shown",
    description: "Use this only after Lensically returned showable=true. It fails if blocking gates made the draft unshowable. Mark the passing draft shown immediately before presenting it to the owner and asking for approve, reject, or revise.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, draft_id: { type: "string" } }, required: ["brand_key", "draft_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "save_self_rejected_draft",
    title: "Save self-rejected draft",
    description: "Use this to save a generated draft that the model rejected internally before showing it to the owner.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, run_id: { type: "string" }, source_card_id: { type: "string" }, text: { type: "string" }, rejection_reason: { type: "string" }, score: { type: "object", additionalProperties: true }, strategy: { type: "object", additionalProperties: true } }, required: ["brand_key", "run_id", "source_card_id", "text", "rejection_reason"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "approve_draft",
    title: "Approve draft",
    description: "Use this after owner approval to mark a shown draft approved and save approval feedback into Lensically memory.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, draft_id: { type: "string" }, feedback_note: { type: "string" }, score: { type: "object", additionalProperties: true }, strategy: { type: "object", additionalProperties: true } }, required: ["brand_key", "draft_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "reject_draft",
    title: "Reject draft",
    description: "Use this after owner rejection to mark a shown draft rejected and save rejection feedback into Lensically memory.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, draft_id: { type: "string" }, rejection_reason: { type: "string" }, feedback_note: { type: "string" }, score: { type: "object", additionalProperties: true }, strategy: { type: "object", additionalProperties: true } }, required: ["brand_key", "draft_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "list_active_gates",
    title: "List active gates",
    description: "Use this to inspect global and account-specific active gates for a stage, lane, or content type.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, stage_scope: { type: "string" }, lane_key: { type: "string" }, content_type: { type: "string" } }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "create_or_update_gate",
    title: "Create or update gate",
    description: "Use this to create or update a scoped operator gate as data instead of hard-coding account-specific rules.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, gate_key: { type: "string" }, display_name: { type: "string" }, description: { type: "string" }, stage_scope: { type: "string" }, lane_scope: { type: "string" }, content_type_scope: { type: "string" }, gate_type: { type: "string" }, severity: { type: "string" }, evaluator: { type: "string" }, active: { type: "boolean" }, order_index: { type: "integer" }, pass_examples: { type: "array", items: {} }, fail_examples: { type: "array", items: {} }, source_memory_ids: { type: "array", items: {} } }, required: ["brand_key", "gate_key", "description", "stage_scope"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "promote_memory_to_gate",
    title: "Promote memory to gate",
    description: "Use this when a strategy memory or owner lesson should become an enforceable scoped operator gate.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, memory_id: { type: "integer" }, gate_key: { type: "string" }, stage_scope: { type: "string" }, lane_scope: { type: "string" }, severity: { type: "string" }, evaluator: { type: "string" } }, required: ["brand_key", "memory_id", "gate_key", "stage_scope"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
];
