import { SCHEDULED_POST_DELETION_REASON_CODES } from "./humanFreeAutonomy";
import { BRAND_KEY_SCHEMA, SOURCE_DRAFT_ANALYSIS_SCHEMA } from "./operatorMcpSchemas";
import type { OperatorMcpToolDefinition } from "./operatorMcpToolDefinitions";

export const OPERATOR_MCP_ADMIN_TOOL_NAMES = [
  "get_monthly_growth_review",
  "selectOperatorKey",
  "confirmOperatorProceed",
  "getGrowthMission",
  "updateGrowthMission",
  "getOperatorDecisionState",
  "proposeOperatorDecision",
  "resolveOperatorDecision",
  "markOperatorDecisionExecuted",
  "getScheduledPostSchedulerState",
  "setScheduledPostSchedulerMode",
  "recoverOverdueScheduledPosts",
  "runApprovedPostCanary",
  "auditScheduledPost",
  "inspectMcpFailure",
  "listMcpTools",
  "readMcpToolDefinition",
  "runMcpTests",
  "getWorkflowStatus",
  "updateWorkflowRequirement",
  "advanceWorkflowStage",
  "prepareFullPreflight",
  "updateGate",
  "runGateSuite",
  "submitAndGateDraft",
] as const;

export type OperatorMcpAdminToolName = typeof OPERATOR_MCP_ADMIN_TOOL_NAMES[number];

export const OPERATOR_MCP_ADMIN_TOOLS: OperatorMcpToolDefinition[] = [
  {
    name: "selectOperatorKey",
    title: "Select operator key",
    description: "Return the exact dynamic four-line Lensically key handshake without loading account data. This tool is stateless because ChatGPT app calls do not preserve MCP session headers.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "confirmOperatorProceed",
    title: "Confirm operator proceed",
    description: "Use the owner's explicit Proceed to restore the selected account, generate the current Growth Mission Brief, and open a discussion-only planning cycle. This writes continuity state but does not authorize account-content mutations.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "getGrowthMission",
    title: "Get Growth Mission Brief",
    description: "Read the selected account's persistent mission, current diagnostic, proposed focus, approval status, execution mode, and revision state after Proceed.",
    inputSchema: {
      type: "object",
      properties: { brand_key: BRAND_KEY_SCHEMA },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "updateGrowthMission",
    title: "Update Growth Mission Brief",
    description: "Persist the owner-model discussion as a flexible mission revision. Use discussion while brainstorming, approved or active only with the owner's exact response, and autonomous_operator only after an explicit owner-authorized full-auto mode change.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        status: { type: "string", enum: ["discussion", "approved", "active", "paused"] },
        execution_mode: { type: "string", enum: ["guided_owner_approval", "autonomous_operator"] },
        mission_patch: {
          type: "object",
          properties: {
            permanent_mission: { type: "string" },
            target_followers: { type: "integer", minimum: 1 },
            growth_phase: { type: "string" },
            current_bottleneck: { type: "string" },
            primary_objective: { type: "string" },
            supporting_objectives: { type: "array", items: { type: "string" } },
            active_experiments: { type: "array", items: { type: "object", additionalProperties: true } },
            proven_patterns: { type: "array", items: { type: "object", additionalProperties: true } },
            fatigued_patterns: { type: "array", items: { type: "object", additionalProperties: true } },
            risks: { type: "array", items: { type: "string" } },
            recommended_next_action: { type: "string" },
            owner_notes: { type: "string" },
          },
          additionalProperties: true,
        },
        owner_response: { type: "string", description: "Exact owner response required to approve or activate a plan and to enable full auto." },
        change_summary: { type: "string" },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "getOperatorDecisionState",
    title: "Get operator decision state",
    description: "Read the active autonomy profile and persisted model-originated decisions for one account. Fresh chats should use this after continuity loads when an autonomy profile is active.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        statuses: { type: "array", items: { type: "string", enum: ["proposed", "approved", "executing", "rejected", "revision_required", "executed", "superseded"] } },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 20 },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "proposeOperatorDecision",
    title: "Propose operator decision",
    description: "Persist a model-originated decision only for a protected destructive, ownership, credential, scheduler-safety, or irreversible business action. Routine Manifest account work and routine engineering do not require this tool or a numerical execution budget.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        decision_key: { type: "string" },
        category: { type: "string", enum: ["strategy", "content", "scheduling", "analytics", "experiment", "workflow", "engineering", "risk"] },
        title: { type: "string" },
        decision: { type: "string" },
        rationale: { type: "string" },
        evidence: { type: "array", items: { type: "object", additionalProperties: true } },
        expected_outcome: { type: "string" },
        risks: { type: "array", items: { type: "string" } },
        reversibility: { type: "string" },
        execution_plan: { type: "string" },
        authorized_tools: { type: "array", items: { type: "string" }, minItems: 1 },
        execution_budget: { type: "object", additionalProperties: { type: "integer", minimum: 1, maximum: 100 } },
        supersedes_decision_id: { type: "string" },
      },
      required: ["brand_key", "category", "title", "decision", "authorized_tools"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "resolveOperatorDecision",
    title: "Resolve operator decision",
    description: "Record the owner's ratification, rejection, or revision request for one protected or irreversible decision. Routine Manifest account work and routine engineering do not require this approval path.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        decision_id: { type: "string" },
        resolution: { type: "string", enum: ["approve", "reject", "revise"] },
        owner_response: { type: "string" },
        revision_request: { type: "string" },
      },
      required: ["brand_key", "decision_id", "resolution", "owner_response"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "markOperatorDecisionExecuted",
    title: "Mark operator decision executed",
    description: "Close an approved or executing decision after its authorized work is complete and persist the outcome and evidence for future learning.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        decision_id: { type: "string" },
        outcome_summary: { type: "string" },
        result_evidence: { type: "array", items: { type: "object", additionalProperties: true } },
      },
      required: ["brand_key", "decision_id", "outcome_summary"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "getScheduledPostSchedulerState",
    title: "Get scheduled-post scheduler state",
    description: "Read the live scheduler mode, alarm and Cron heartbeats, overdue counts, and exact post IDs selected by the latest run.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "setScheduledPostSchedulerMode",
    title: "Set scheduled-post scheduler mode",
    description: "Explicitly set the universal scheduler to paused, canary, or normal. Canary requires exactly one scheduled_post_id, processes at most one due record, and automatically returns to paused after its attempt.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        mode: { type: "string", enum: ["paused", "canary", "normal"] },
        scheduled_post_id: { type: "integer", minimum: 1 },
        reason: { type: "string" },
        owner_response: { type: "string", description: "Exact owner approval from the current conversation. When present, Lensically persists ratification before executing the protected scheduler change." },
      },
      required: ["mode", "reason"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "recoverOverdueScheduledPosts",
    title: "Recover or retire scheduled posts while paused",
    description: "While the universal scheduler is paused, retire up to 25 approved unpublished future or overdue rows through unobserved operational receipts, or move overdue rows to explicit future timestamps. Recovery requires an objective structured reason code and never creates model-learning evidence.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        actions: {
          type: "array",
          minItems: 1,
          maxItems: 25,
          items: {
            type: "object",
            properties: {
              scheduled_post_id: { type: "integer", minimum: 1 },
              action: { type: "string", enum: ["retire", "reschedule"] },
              scheduled_time: { type: "string", description: "Required future ISO timestamp when action is reschedule." },
            },
            required: ["scheduled_post_id", "action"],
            additionalProperties: false,
          },
        },
        reason_code: { type: "string", enum: SCHEDULED_POST_DELETION_REASON_CODES },
        reason_detail: { type: "string", description: "Optional factual recovery detail. Do not include taste feedback or performance predictions." },
        owner_response: { type: "string", description: "Exact owner approval from the current conversation for this bounded protected recovery." },
      },
      required: ["actions", "reason_code"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "runApprovedPostCanary",
    title: "Run approved post canary",
    description: "Run exactly one owner-approved scheduled-post delivery canary for the supplied post ID. The scheduler automatically returns to paused after the attempt. This compact command maps to the protected scheduler-control authority without exposing a mode field through generic client arguments.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        scheduled_post_id: { type: "integer", minimum: 1 },
        reason: { type: "string" },
        owner_response: { type: "string", description: "Exact owner approval when authorization has not already been persisted." },
      },
      required: ["brand_key", "scheduled_post_id", "reason"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "auditScheduledPost",
    title: "Audit scheduled post",
    description: "Read one selected-account scheduled record by ID, including status, publication ID, attempt timestamps, publication timestamp, and stored error state.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        scheduled_post_id: { type: "integer", minimum: 1 },
      },
      required: ["brand_key", "scheduled_post_id"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "inspectMcpFailure",
    title: "Inspect MCP failure",
    description: "Classify an MCP or handler failure and return the smallest source-defined repair path without creating a database record.",
    inputSchema: { type: "object", properties: { tool_name: { type: "string" }, error_response: { type: "object", additionalProperties: true }, error_text: { type: "string" } }, additionalProperties: false },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "listMcpTools",
    title: "List active MCP tools",
    description: "List the active source-defined Lensically internal handlers. This action is read-only and cannot execute another tool.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "readMcpToolDefinition",
    title: "Read MCP tool definition",
    description: "Read one active source-defined MCP handler and its typed input schema.",
    inputSchema: { type: "object", properties: { tool_name: { type: "string" } }, required: ["tool_name"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "runMcpTests",
    title: "Run MCP tests",
    description: "Run the bounded Execution Kernel campaign. Routes validates the complete surface; each read segment executes only its bounded read-only group so one Worker invocation never exceeds external-request limits.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        segment: {
          type: "string",
          enum: [
            "routes",
            "engineering_reads",
            "admin_reads",
            "account_reads_a",
            "account_reads_b",
            "engineering_mutations",
            "admin_mutations",
            "account_mutations_a",
            "account_mutations_b",
            "s0",
            "s1",
            "s2",
            "s3",
            "s4",
            "s5",
            "s6",
            "s7",
            "s8"
          ],
          default: "routes",
        },
      },
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "getWorkflowStatus",
    title: "Get workflow status",
    description: "Inspect the selected account's active operator workflow, context admission, source card, generation, draft, scheduling, and blocker status.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, workflow_session_id: { type: "string" } }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "updateWorkflowRequirement",
    title: "Update workflow requirement",
    description: "Create or update a DB-backed workflow requirement that blocks stage advancement until its completion rule passes.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, stage: { type: "string" }, required_sections: { type: "array", items: { type: "string" } }, completion_rule: { type: "string" }, enforcement_type: { type: "string", enum: ["block", "warn"] }, active: { type: "boolean" } }, required: ["stage", "required_sections", "completion_rule"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "advanceWorkflowStage",
    title: "Advance workflow stage",
    description: "Advance an operator workflow only if DB-backed requirements for the target stage pass.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, workflow_session_id: { type: "string" }, target_stage: { type: "string" } }, required: ["brand_key", "target_stage"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "prepareFullPreflight",
    title: "Prepare full preflight",
    description: "Run server-side preflight collection for the selected account and record complete/partial context admission before serious workflow advancement.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, workflow_session_id: { type: "string" } }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "updateGate",
    title: "Update gate",
    description: "Create or update an account-scoped operator gate through the admin MCP surface.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, gate_key: { type: "string" }, display_name: { type: "string" }, description: { type: "string" }, stage_scope: { type: "string" }, lane_scope: { type: "string" }, content_type_scope: { type: "string" }, gate_type: { type: "string" }, severity: { type: "string" }, evaluator: { type: "string" }, active: { type: "boolean" }, order_index: { type: "integer" }, pass_examples: { type: "array", items: {} }, fail_examples: { type: "array", items: {} }, source_memory_ids: { type: "array", items: {} } }, required: ["brand_key", "gate_key", "description", "stage_scope"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "runGateSuite",
    title: "Run gate suite",
    description: "Run all active operator gates for source cards or drafts, including source transformation, account-wide historical owner rejection review, and required-gate execution. For historical_owner_rejection_gate, include the exact rejection-context fingerprint and reviewed count from the generation run. Missing historical review or any missing blocking gate must keep showable=false. This remains a silent internal workflow stage.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, source_card_id: { type: "string" }, draft_text: { type: "string" }, stage: { type: "string" }, lane_key: { type: "string" }, content_type: { type: "string" }, draft_analysis: SOURCE_DRAFT_ANALYSIS_SCHEMA, model_gate_results: { type: "array", items: { type: "object", additionalProperties: true } } }, required: ["brand_key", "stage"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "submitAndGateDraft",
    title: "Submit and gate draft",
    description: "Submit a candidate draft, record source-contract evidence, run every mandatory Lensically gate, and return showable/blocking status in one admin MCP call. Include historical_owner_rejection_gate evidence using the exact persisted account rejection-context fingerprint and reviewed count. The backend blocks explicit banned surfaces, rejected-draft near-matches, incomplete historical review, and missing gate execution. Present the draft only when showable=true.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, run_id: { type: "string" }, source_card_id: { type: "string" }, text: { type: "string" }, draft_text: { type: "string" }, draft_index: { type: "integer" }, score: { type: "object", additionalProperties: true }, strategy: { type: "object", additionalProperties: true }, draft_analysis: SOURCE_DRAFT_ANALYSIS_SCHEMA, model_gate_results: { type: "array", items: { type: "object", additionalProperties: true } } }, required: ["brand_key", "run_id", "source_card_id"], additionalProperties: false },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
];
