import { OPERATOR_WORKFLOW_TEMPLATE_KEY } from "./operatorMcpConstants";
import {
  BRAND_KEY_SCHEMA,
  SOURCE_TRANSFORMATION_CONTRACT_SCHEMA,
} from "./operatorMcpSchemas";
import type { OperatorMcpToolDefinition } from "./operatorMcpToolDefinitions";

export const OPERATOR_MCP_ACCOUNT_FOUNDATION_TOOL_NAMES = [
  "list_accounts",
  "get_account_state",
  "read_lensically_ui_surface",
  "discard_manifest_review_batch",
  "get_hourly_coverage",
  "claim_manifest_review_batch",
  "get_manifest_review_batch",
  "attach_manifest_review_draft",
  "skip_manifest_review_source",
  "schedule_manifest_review_batch",
  "start_workflow_session",
  "admit_context",
  "get_production_board",
  "list_source_candidates",
  "delete_saved_pattern_source",
  "draw_source_candidate_batch",
  "audit_published_post_lineage",
  "recover_published_post_lineage",
  "create_all_missing_manifest_source_cards",
  "prepare_manifest_source_card_backfill",
  "get_source_candidate_batch",
] as const;

export type OperatorMcpAccountFoundationToolName = typeof OPERATOR_MCP_ACCOUNT_FOUNDATION_TOOL_NAMES[number];

export const OPERATOR_MCP_ACCOUNT_FOUNDATION_TOOLS: OperatorMcpToolDefinition[] = [
  {
    name: "list_accounts",
    title: "List Lensically accounts",
    description: "Use this when you need to discover the available Lensically accounts before choosing a brand_key.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "get_account_state",
    title: "Get account state",
    description: "Use this when you need the current workflow session, active source card, draft counts, scheduled count, and gate status for one Lensically account.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "read_lensically_ui_surface",
    title: "Read Lensically UI surface",
    description: "Read the same authoritative account data used by Lensically Dashboard, Followers, Insights, Post Archive, or Saved Patterns. Every paginated record remains reachable through page, cursor, limit, and order inputs.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        surface: { type: "string", enum: ["dashboard", "followers", "insights", "post_archive", "saved_patterns"] },
        order: { type: "string", enum: ["recent", "top", "newest", "likes"] },
        page: { type: "integer", minimum: 1, default: 1 },
        limit: { type: "integer", minimum: 1, maximum: 200, default: 100 },
        cursor: { type: "string" },
        cursor_depth: { type: "integer", minimum: 1, maximum: 250 },
      },
      required: ["brand_key", "surface"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "discard_manifest_review_batch",
    title: "Discard Manifest review batch",
    description: "Retire one stale Manifest review batch so continuity cannot resume it. Preserve all underlying Saved Pattern, archive, source-lineage, and analytics records for future independent use.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        review_batch_id: { type: "string" },
        reason: { type: "string" },
      },
      required: ["brand_key", "reason"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "get_hourly_coverage",
    title: "Get hourly publishing coverage",
    description: "Inspect the selected account schedule from the next viable hour forward and return the earliest incomplete publishing day, its open hourly slots, and the next open slot. Past missed hours are never backfilled. When a Manifest cycle_id is supplied, also return next_cycle_plan_item with the exact locked plan UUID and source-backed execution contract required by persist_manifest_autonomous_post.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        start_date: { type: "string" },
        timezone: { type: "string" },
        horizon_days: { type: "integer", minimum: 1, maximum: 60, default: 14 },
        cycle_id: { type: "string", description: "Optional autonomous cycle ID. When present, append this coverage reconciliation to that cycle's immutable receipt." },
        operation_id: { type: "string", description: "Stable identity for this coverage checkpoint." },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "claim_manifest_review_batch",
    title: "Claim Manifest four-post review batch",
    description: "Claim up to four random qualified Manifest sources for one production date. Claims are durable across chats and prevent the same stable source identity from being used twice on that date. Set fresh_draw=true only for an owner-approved source-draw reset.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        production_date: { type: "string" },
        timezone: { type: "string" },
        batch_size: { type: "integer", minimum: 1, maximum: 4, default: 4 },
        source_types: { type: "array", items: { type: "string" } },
        fresh_draw: { type: "boolean" },
      },
      required: ["brand_key", "production_date"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "get_manifest_review_batch",
    title: "Get Manifest review batch",
    description: "Restore the active canonical four-post guided-review batch with stable item numbers, source text, generated drafts, and decision state. Do not call this during an autonomous Manifest cycle; autonomous execution proceeds from prepare_manifest_autonomous_cycle directly to persist_manifest_autonomous_post. A missing guided-review batch is a normal non-blocking state.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        review_batch_id: { type: "string" },
        production_date: { type: "string" },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "attach_manifest_review_draft",
    title: "Attach passing draft to Manifest review item",
    description: "Associate one showable shown draft with Post 1, 2, 3, or 4 in the active review batch after silent source-card generation and gates.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        review_batch_id: { type: "string" },
        item_number: { type: "integer", minimum: 1, maximum: 4 },
        source_card_id: { type: "string" },
        generation_run_id: { type: "string" },
        draft_id: { type: "string" },
      },
      required: ["brand_key", "review_batch_id", "item_number", "draft_id"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "skip_manifest_review_source",
    title: "Skip or delete Manifest source",
    description: "Apply an owner source-level decision to a numbered review item. current_day keeps the source unavailable only for that production date. delete_source permanently excludes a Saved Pattern from future draws while preserving its post, analytics, cards, and lineage; own-account posts cannot be deleted as sources.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        review_batch_id: { type: "string" },
        item_number: { type: "integer", minimum: 1, maximum: 4 },
        scope: { type: "string", enum: ["current_day", "delete_source"] },
        reason: { type: "string" },
      },
      required: ["brand_key", "review_batch_id", "item_number", "scope"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "schedule_manifest_review_batch",
    title: "Schedule approved Manifest review items",
    description: "Schedule approved numbered review items into the earliest open hourly slots for their production date, preserving item order. Return confirmed persisted times only after each schedule succeeds.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        review_batch_id: { type: "string" },
        item_numbers: { type: "array", items: { type: "integer", minimum: 1, maximum: 4 } },
      },
      required: ["brand_key", "review_batch_id"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "start_workflow_session",
    title: "Start workflow session",
    description: "Use this when beginning the universal content_operator_v1 workflow for a selected Lensically account.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_template_key: { type: "string", default: OPERATOR_WORKFLOW_TEMPLATE_KEY },
        notes: { type: "string" },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "admit_context",
    title: "Admit context coverage",
    description: "Use this to record which Lensically data sections were admitted for a workflow and whether the data is partial, complete, or sufficient for the objective.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        admission_scope: { type: "string", enum: ["full_preflight", "source_card_selection", "generation_context", "growth_review", "scheduling_check"] },
        sections: { type: "array", items: { type: "object", additionalProperties: true } },
        snapshot_id: { type: "string" },
        notes: { type: "string" },
      },
      required: ["brand_key", "admission_scope", "sections"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "get_production_board",
    title: "Get production board",
    description: "Use this to read account-scoped production board items such as lane priorities, cooldowns, warnings, source pools, and recommendations.",
    inputSchema: { type: "object", properties: { brand_key: BRAND_KEY_SCHEMA, workflow_session_id: { type: "string" } }, required: ["brand_key"], additionalProperties: false },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "list_source_candidates",
    title: "List source candidates",
    description: "Use this to find candidate sources for a source card from archive posts, saved patterns, recent insights, memory, drafts, or scheduled posts.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        lane_key: { type: "string" },
        source_types: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 50 },
        offset: { type: "integer", minimum: 0, default: 0 },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "delete_saved_pattern_source",
    title: "Delete saved pattern source",
    description: "Delete one owner-selected saved pattern so it cannot enter future source draws. If it has an unused draft source card, unlink and delete that draft card too. Requires explicit owner approval.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        pattern_id: { type: "integer", minimum: 1 },
        source_card_id: { type: "string" },
        owner_approval: { type: "string" },
      },
      required: ["brand_key", "pattern_id", "owner_approval"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  },
  {
    name: "draw_source_candidate_batch",
    title: "Draw Manifest source candidate batch",
    description: "Draw and persist the 24 unique Manifest sources for one production day from all sources with at least 1,000 verified likes. Uses uniform random selection without replacement, preserves draw order as posting order, and applies no cross-day cooldown or performance weighting.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        source_types: { type: "array", items: { type: "string" } },
      },
      required: ["brand_key", "workflow_session_id"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "audit_published_post_lineage",
    title: "Audit published winner lineage",
    description: "Read a bounded set of high-performing published posts and verify every lineage stage from source selection through metric snapshots. Returns complete and incomplete posts without mutating account data.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        minimum_likes: { type: "integer", minimum: 1, default: 1000 },
        days: { type: "integer", minimum: 1, maximum: 90, default: 30 },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 25 },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "recover_published_post_lineage",
    title: "Recover published post lineage",
    description: "Recover one proven Manifest Saved Pattern family by creating or reusing its canonical source selection and source card, then attaching known published posts, dedicated generation runs, drafts, schedules, and metric snapshots. Use only when the historical Saved Pattern source is known and verified.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        workflow_session_id: { type: "string" },
        saved_pattern_id: { type: "integer", minimum: 1 },
        published_post_ids: { type: "array", minItems: 1, maxItems: 10, items: { type: "string" } },
        source_card: {
          type: "object",
          properties: {
            title: { type: "string" },
            lane_key: { type: "string" },
            source_mechanism: { type: "string" },
            required_product: { type: "string" },
            transformation_contract: SOURCE_TRANSFORMATION_CONTRACT_SCHEMA,
            forbidden_surfaces: { type: "array", items: {} },
            danger_surfaces: { type: "array", items: {} },
            pass_conditions: { type: "array", items: {} },
            fail_conditions: { type: "array", items: {} },
            recommended_direction: { type: "string" },
          },
          required: ["title", "source_mechanism", "required_product", "forbidden_surfaces", "pass_conditions", "fail_conditions"],
          additionalProperties: false,
        },
      },
      required: ["brand_key", "workflow_session_id", "saved_pattern_id", "published_post_ids", "source_card"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "create_all_missing_manifest_source_cards",
    title: "Create all missing Manifest source cards",
    description: "Create and lock the next bounded batch of Manifest Mental Saved Patterns that do not yet have linked source cards. Continue calling with a new operation_id until status=complete and remaining_count=0. Each Saved Pattern receives durable source-selection lineage and an immediately usable locked canonical source card.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        limit: { type: "integer", minimum: 1, maximum: 4, default: 4 },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  },
  {
    name: "prepare_manifest_source_card_backfill",
    title: "Prepare Manifest source-card backfill",
    description: "Read the next bounded batch of Manifest Mental Saved Patterns that do not yet have linked source cards. Continue calling this after each batch until status=complete. A normal successful run ends only when every Saved Pattern is carded; report an uncarded count only after a forced interruption.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        limit: { type: "integer", minimum: 1, maximum: 25, default: 8 },
      },
      required: ["brand_key"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  {
    name: "get_source_candidate_batch",
    title: "Get source candidate batch",
    description: "Retrieve one persisted source draw and its immutable source snapshots in posting order.",
    inputSchema: {
      type: "object",
      properties: {
        brand_key: BRAND_KEY_SCHEMA,
        source_batch_id: { type: "string" },
      },
      required: ["brand_key", "source_batch_id"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
];
